var build = Builder.Create("GCC");
build.Init();
build.Cortex = 3;
build.Output = "GCC";
build.Defines.Add("STM32F1");
build.AddIncludes("..\\", false);
build.AddFiles("..\\Core");
build.AddFiles("..\\Kernel");
build.AddFiles("..\\Device");
build.AddFiles("..\\", "*.c;*.cpp", false);
build.AddFiles("..\\Security", "*.cpp");
build.AddFiles("..\\Board");
build.AddFiles("..\\Storage");
build.AddFiles("..\\App");
build.AddFiles("..\\Drivers");
build.AddFiles("..\\Net");
build.AddFiles("..\\Test");
build.AddFiles("..\\TinyIP", "*.c;*.cpp", false, "HttpClient");
build.AddFiles("..\\Message");
build.AddFiles("..\\TinyNet");
build.AddFiles("..\\TokenNet");
build.Libs.Clear();
build.CompileAll();
build.BuildLib("..\\libSmartOS_M3.a");

build.Debug = true;
build.CompileAll();
build.BuildLib("..\\libSmartOS_M3.a");
